server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8090
        type: sync
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
            scope: openid, profile
            client-name: oidc-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000

messages:
  base-uri: http://127.0.0.1:8090/messages
